### ISSUE TITLE
Support JSON:API content-type

### ISSUE THREAD

**Issue by zekth** [pb33f/libopenapi-validator#1]
Currently as stated it supports only JSON: https://github.com/pb33f/libopenapi-validator/blob/35aed242bc51fa7f1912bb1e25fa906e2edc2b59/requests/validate_body.go#L34

We should support https://jsonapi.org/ format like `application/vnd.api+json`

**Comment by daveshanley** [comment]
This is out of scope for libopenapi. I want to keep the library tightly focused on OpenAPI and not mix in the different concepts and foundations of JSON:API

**Comment by zekth** [comment]
It is part of specification: https://swagger.io/specification/

**Comment by daveshanley** [comment]
Oh I see what you mean, you just want support for those mime types, vs actually supporting validation of different schema types outside of JSON schema. 

I would avoid looking at the code you see today, as the code that will make it into the final cut, a lot of this is me exploring out concepts and patterns.

**Comment by daveshanley** [comment]
Try v0.0.1 and open any issues you may find.
