### ISSUE TITLE
A spec with an empty `content` block will always fail to validate

### ISSUE THREAD

**Issue by jamietanna** [pb33f/libopenapi-validator#14]
In the case that an OpenAPI spec is not defining the response body - which can be a valid thing to do - we receive an error:

```
validator.go:50: Error: GET / 200 operation response content type '' does not exist, Reason: The content type '' of the GET response received has not been defined, it's an unknown type, Line: 11, Column: 11
```

For spec:

```yaml
openapi: "3.0.0"
info:
  title: Healthcheck
  version: '0.1.0'
paths:
  /health:
    get:
      responses:
        '200':
          description: pet response
          content: {}
```

There's quite a few other folks doing this, too https://github.com/search?q=%22content%3A+%7B%7D%22+language%3Ayaml&type=code so not sure if maybe this needs to be something we can opt-in to allowing maybe? Not sure if it's something we want to have on-by-default

**Comment by daveshanley** [comment]
Hmm... OK, I will look into it.

**Comment by daveshanley** [comment]
Should be good to go now, the validator now supports empty content definitions. It will only get upset if there is content defined but the types can't be found

**Comment by jamietanna** [comment]
Thanks very much, appreciate the super speedy fixes!

**Comment by daveshanley** [comment]
Most welcome, my pleasure.
