### ISSUE TITLE
Response `content-type` is not validated

### ISSUE THREAD

**Issue by jamietanna** [pb33f/libopenapi-validator#2]
As per the [changes on this branch](https://gitlab.com/jamietanna/oapi-codegen-example-project/-/tree/libopenapi-validator) of one of my projects, returning an invalid `content-type` header in either the implementation or the OpenAPI spec leads to no failure.

**Comment by daveshanley** [comment]
Hi, 

Can you help me a little more? I don't have context on your project, can you include some code  and a spec I can use to re-create your issue?

**Comment by jamietanna** [comment]
Hey sure thing! So in [this commit](https://gitlab.com/jamietanna/oapi-codegen-example-project/-/commit/09782d162e5930de870c85590e04e98c0798155d) I'm returning a different `content-type` than is expected [in the spec](https://gitlab.com/jamietanna/oapi-codegen-example-project/-/blob/09782d162e5930de870c85590e04e98c0798155d/openapi.yaml?plain=1#L19)

**Comment by daveshanley** [comment]
OK, interesting.. I see now. I think I know what the issue is. Will fix.

**Comment by jamietanna** [comment]
If I remove `json` from the string, I still see a passing test

**Comment by daveshanley** [comment]
I am struggling with this one as I have multiple tests in place to catch this: 

https://github.com/pb33f/libopenapi-validator/blob/0.0.2/responses/validate_body_test.go#L19

I even created a new test to simulate your situation
https://github.com/pb33f/libopenapi-validator/blob/0.0.2/validator_test.go#L292

Still passed.

**Comment by daveshanley** [comment]
I have re-created this exact example and added a test. 

https://github.com/pb33f/libopenapi-validator/blob/0.0.2/validator_test.go#L1013

The test passes. I cannot re-create this issue.
