### ISSUE TITLE
Path not found error handling

### ISSUE THREAD

**Issue by zekth** [pb33f/libopenapi-validator#4]
In the current state of the api the `ValidateHttpRequest` does the path lookup and the request validation at the same time. It ouputs an error slice of `errors.ValidationError`.
Issue is when you want to do composition in middleware you end up with logic like:
```go
skipServe := false
valid, validationErrs := docValidator.ValidateHttpRequest(r)
if !valid {
	for _, e := range validationErrs {
		if opts.RouteNotFoundHook != nil && e.ValidationType == "path" && e.ValidationSubType == "missing" {
			skipServe = opts.RouteNotFoundHook(e, w, r)
			break
		}

		if opts.RouteValidationErrorHook != nil {
			skipServe = opts.RouteValidationErrorHook(e, w, r)
			break
		}
	}
}
```

Solutions:
- Expose a specific error for a path not found
- Expose a function to check if the error is a path not found

wdyt?

**Comment by daveshanley** [comment]
Hi, 

Have you seen this? 

https://github.com/pb33f/libopenapi-validator/blob/main/requests/request_body.go#L26

and

https://github.com/pb33f/libopenapi-validator/blob/main/paths/paths.go#L22

The top level validator does not give you control over things like this, however the individual validators do.

**Comment by zekth** [comment]
I'd rather stick to the use of `path`. I was throwing this as in the code it already does this path check in the `validateRequest` function: https://github.com/pb33f/libopenapi-validator/blob/e86a2da1617bda791854b5fdfba0d61475996cf5/validator.go#L122-L133

If i want to do composition like describe i'd have preferred to not repeat the operation twice. However i think it's better this way than to rebuild an adhoc composed validation function.

**Comment by daveshanley** [comment]
Would `IsPathMissingError() bool` as a method on `errors.ValidationError` work?

**Comment by zekth** [comment]
Looks good to me
