### ISSUE TITLE
/ server breaks validation

### ISSUE THREAD

**Issue by emilien-puget** [pb33f/libopenapi-validator#62]
```yaml
openapi: 3.1.0
servers:
  - url: /
paths:
  /burgers/{burgerId}/locate:
    patch:
      operationId: locateBurger
      parameters:
        - name: burgerId
          in: path
          required: true
          schema:
            type: string
            format: uuid	
```

a validation of a http request for that open api path will yield an unexpected result

> Error: Path parameter 'burgerId' failed to validate, Reason: The path parameter 'burgerId' is defined as an string, however it failed to pass a schema validation, Validation Errors: [Reason: 'locate' is not valid 'uuid', Location: /format

the cause is this function
```go

// StripRequestPath strips the base path from the request path, based on the server paths provided in the specification
func StripRequestPath(request *http.Request, document *v3.Document) string {

	basePaths := getBasePaths(document)

	// strip any base path
	stripped := stripBaseFromPath(request.URL.Path, basePaths)
	if request.URL.Fragment != "" {
		stripped = fmt.Sprintf("%s#%s", stripped, request.URL.Fragment)
	}
	return stripped
}
```

which remove the base path from the request path, in our case it yields
`burgers/{burgerId}/locate`

but the foundPath is still valued as 
`/burgers/{burgerId}/locate`

if we want to support the / server url, we could modify the StripRequestPath to make sure that a path always starts with a / even if we drop it during the stripBaseFromPath phase.

wdyt ?

something like this
```go

// StripRequestPath strips the base path from the request path, based on the server paths provided in the specification
func StripRequestPath(request *http.Request, document *v3.Document) string {

	basePaths := getBasePaths(document)

	// strip any base path
	stripped := stripBaseFromPath(request.URL.Path, basePaths)
	if request.URL.Fragment != "" {
		stripped = fmt.Sprintf("%s#%s", stripped, request.URL.Fragment)
	}
	if len(stripped) > 0 && !strings.HasPrefix(stripped, "/") {
		stripped = "/" + stripped
	}
	return stripped
}
```

**Comment by emilien-puget** [comment]
i madea pr with the tests and a code that may fix this issue here https://github.com/pb33f/libopenapi-validator/pull/63

**Comment by daveshanley** [comment]
Thank you for your continued high quality contributions!

Added in `v0.0.47`
