### ISSUE TITLE
Handles optional request bodies

### ISSUE THREAD

**Issue by emilien-puget** [pb33f/libopenapi-validator#70]
As i just discovered, request bodies are optional by default.
see https://spec.openapis.org/oas/v3.1.0#fixed-fields-10 or https://swagger.io/docs/specification/describing-request-body/
 this dear library doesn't handle such cases
https://github.com/pb33f/libopenapi-validator/blob/688b7a2e81d820bed7d96b28af6fdebd3d52cea9/requests/validate_body.go#L41

as we can see above, if an operation has a request body, we will require to have a content type set, however that request body could be not required which means that a content type should not be required.

i haven't go any further in my investigation, maybe the underlying lib is already capable of handling such cases, any if we agree that this is not an expected behavior i can propose a fix in a few hours/days.

**Comment by daveshanley** [comment]
Yeah, I agree if `required` is set to false (which as you pointed out, is the default), then the library should be able to handle it.

**Comment by emilien-puget** [comment]
here it is https://github.com/pb33f/libopenapi-validator/pull/71
