### ISSUE TITLE
Concurrency/Mutex Question

### ISSUE THREAD

**Issue by JemDay** [pb33f/libopenapi-validator#93]
HI,

The line referenced below creates a mutex of global-scope that is only used in the `runValidation` function meaning that it essentially get shared across all running instances of the function.

Before i open a PR to move the mutex inside the `runValidation` function was there a reason behind making it global. 

https://github.com/pb33f/libopenapi-validator/blob/696235ecd56ed0a28e34f28ae1e8ab3bf69eb0aa/validator.go#L319

**Comment by JemDay** [comment]
Thanks @daveshanley - Is it safe to assume that the validator "as a whole" is reentrant; ie if I've built  and cached) a validator can I hit that instance concurrently from different go-routines

**Comment by daveshanley** [comment]
Thats the goal, yes :)

**Comment by JemDay** [comment]
Thanks  for the response .. closing this issue
